version: "3.3"

services:
  server:
    build: ./server
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 5000:5000
    volumes:
      - ./server:/app/server
      - /app/server/node_modules

  client:
    build: ./client
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    stdin_open: true
    depends_on:
      - server
