name: Node.js CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
  test-server:
    name: server-test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: | 
        cd server
        npm ci
        npm run build --if-present
        npm run test-coverage
      env:
        CI: true

  test-client:
    name: client-test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name : echo the path
      run: echo $PWD

    - name: go to client directory 
      run: cd client
      working-directory: ./client

    - name: Install dependencies
      run: npm ci
      working-directory: ./client

    - name: Run the tests
      run: npm run test-coverage
      working-directory: ./client
    # - name: Build
    #   run: npm run build
    # - name: npm install, build, and test
    
      # run: | 
      # cd client
      # npm ci
      # npm run build --if-present 
      # npm run test-coverage
      env:
        CI: true 